[package]
name = "rox"
version = "0.1.0"
authors = ["freemasen <r.f.masen@gmail.com>"]
edition = "2018"


[dependencies]
log = "0.4"
pretty_env_logger = "0.3"

[lib]
name = "rox"
path = "src/lib.rs"

[[bin]]
name = "roxi"
path = "src/main.rs"