[package]
name = "roxc"
version = "0.1.0"
authors = ["freemasen <r.f.masen@gmail.com>"]
edition = "2018"


[dependencies]
log = "0.4"
hash-chain = "0.3"
rox_shared = { path = "../rox_shared" }

[dev-dependencies]
pretty_env_logger = "0.3"


[features]
default = []
debug = []